### ISSUE TITLE
Квест12 В начале диалога Лиза в окне но по диалогу разговор Мэри и Евы

### ISSUE THREAD

**Issue by Alexander7kuc** [Monotronic/Island-Of-Happiness#125]
![1](https://user-images.githubusercontent.com/44965588/50042598-fac28c80-006d-11e9-94ca-81c1721a5bb1.png)
![1 1](https://user-images.githubusercontent.com/44965588/50042601-044bf480-006e-11e9-8806-3de0ed9009aa.png)

**Comment by VladimirFedorenkokhalilov1987** [comment]
исправил
