### ISSUE TITLE
Квест 143 Вертолет не приземлился, часть лопастей за текстурой, используется анимация взлета вертолета вместо приземления, Доллар просто появился возле других а не вышел из вертолета. У него есть анимация ходьбы спиной, но не используется.

### ISSUE THREAD

**Issue by Alexander7kuc** [Monotronic/Island-Of-Happiness#143]
![screenshot_13](https://user-images.githubusercontent.com/44965588/50042798-39a61180-0071-11e9-8c9d-7d777dba7765.png)

**Comment by VladimirFedorenkokhalilov1987** [comment]
часть лопастей за текстурой - обусловлено строением вертолета, а именно blades (2), из-за поворота по оси x, лопасти пропадают при вращении  blades (2) по оси z

**Comment by Alexander7kuc** [comment]
> часть лопастей за текстурой - обусловлено строением вертолета, а именно blades (2), из-за поворота по оси x, лопасти пропадают при вращении blades (2) по оси z

Исправил

**Comment by VladimirFedorenkokhalilov1987** [comment]
fixed
