### ISSUE TITLE
Квест 145 Позиция Евы и доллара при передаче контракта. Лиза вместе с евой читают контракт

### ISSUE THREAD

**Issue by Alexander7kuc** [Monotronic/Island-Of-Happiness#144]
![screenshot_14](https://user-images.githubusercontent.com/44965588/50042811-7c67e980-0071-11e9-8f56-f4903cb9d2f7.png)
![screenshot_15](https://user-images.githubusercontent.com/44965588/50042814-812c9d80-0071-11e9-843d-f69ae13032e5.png)

**Comment by VladimirFedorenkokhalilov1987** [comment]
fixed
