### ISSUE TITLE
Квест 89, машина едет сквозь препятствия (заборы, знаки)

### ISSUE THREAD

**Issue by Alexander7kuc** [Monotronic/Island-Of-Happiness#51]

**Comment by Marvell255** [comment]
![default](https://user-images.githubusercontent.com/38038834/48411480-4f5ea900-e74a-11e8-9e60-26f265df5208.png)

**Comment by VladimirFedorenkokhalilov1987** [comment]
fixed
машина пропадает когда хиппи садятся в нее
