### ISSUE TITLE
Локация свадьбы: коробка

### ISSUE THREAD

**Issue by Marvell255** [Monotronic/Island-Of-Happiness#52]
![2018-11-13 13 51 49](https://user-images.githubusercontent.com/38038834/48411822-6b167f00-e74b-11e8-96e8-e26559046422.png)

**Comment by Marvell255** [comment]
Дополнительно не хватает меша на коробке для навигации.

**Comment by VladimirFedorenkokhalilov1987** [comment]
добавил CheckStatusOnMap, добавил меш
