### ISSUE TITLE
Квест 125 Диалог начался когда динозавр стоит у бассейна

### ISSUE THREAD

**Issue by Marvell255** [Monotronic/Island-Of-Happiness#96]
![image](https://user-images.githubusercontent.com/38038834/49036980-b9069a80-f1c1-11e8-942b-cdbd410964de.png)
Квест 125 Диалог начался когда динозавр стоит у бассейна бэтмен и дино подошли после диалога после чего дино снял крышку с лица. Позиции персонажей выглядят неуместно. У динозавра есть анимация на окно, подключена другая.

**Comment by VladimirFedorenkokhalilov1987** [comment]
исправил
